### ISSUE TITLE
Detectron only automatically caches URLs in the Detectron S3 bucket

### ISSUE THREAD

**Issue by zsw667291** [Johnqczhang/densepose_installation#2]
```
python tools/infer_simple.py     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml     --output-dir DensePoseData/infer_out/     --image-ext jpg     --wts https://dl.fbaipublicfiles.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl     DensePoseData/demo_data/demo_im.jpg
/home/SENSETIME/zhushiwei/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Found Detectron ops lib: /home/SENSETIME/zhushiwei/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Traceback (most recent call last):
  File "tools/infer_simple.py", line 176, in <module>
    main(args)
  File "tools/infer_simple.py", line 117, in main
    args.weights = cache_url(args.weights, cfg.DOWNLOAD_CACHE)
  File "/home/SENSETIME/zhushiwei/sense_work/DensePose/detectron/utils/io.py", line 100, in cache_url
    'bucket: {}').format(_DETECTRON_S3_BASE_URL)
AssertionError: Detectron only automatically caches URLs in the Detectron S3 bucket: https://dl.fbaipublicfiles.com/detectron

```
i download  git clone https://github.com/Johnqczhang/DensePose $DENSEPOSE
run the code than i recieve the following code
how can i fix this problem?
thx!!!!

**Comment by Johnqczhang** [comment]
Hi @zsw667291, please change [line-28](https://github.com/Johnqczhang/DensePose/blob/master/detectron/utils/io.py#L28) as `_DETECTRON_S3_BASE_URL = 'https://dl.fbaipublicfiles.com'`

**Comment by zsw667291** [comment]
> Hi @zsw667291, please change [line-28](https://github.com/Johnqczhang/DensePose/blob/master/detectron/utils/io.py#L28) as `_DETECTRON_S3_BASE_URL = 'https://dl.fbaipublicfiles.com'`

it works !!! 
thanks a lot!
