### ISSUE TITLE
issue when running python $DENSEPOSE/detectron/tests/test_zero_even_op.py

### ISSUE THREAD

**Issue by hanabi7** [Johnqczhang/densepose_installation#8]
undefined symbol: _ZN6caffe219CPUOperatiorRegistryB5cxx11Ev

**Comment by Johnqczhang** [comment]
http://linkinpark213.com/2018/11/18/densepose-minesweeping/#2-10-Undefined-symbol-ZN6caffe219CPUOperatorRegistryB5cxx11Ev

**Comment by hanabi7** [comment]
i install pytorch=1.1.0 with conda, do i have to install pytorch from source code to the newest version of pytorch?

**Comment by hanabi7** [comment]
my gcc version is correct

**Comment by Johnqczhang** [comment]
> i install pytorch=1.1.0 with conda, do i have to install pytorch from source code to the newest version of pytorch?

I'm not sure if it works if you install the latest version of pytorch from source code. Using pytorch-1.1.0 installed from conda and gcc-4.9.2 really works for me. Have you tried solution in this [issue](https://github.com/linkinpark213/linkinpark213.github.io/issues/12#issuecomment-476222914)?

**Comment by SriRamGovardhanam** [comment]
Hello 
i have checked your guide perfectly
I am facing OS Error issue

`Traceback (most recent call last):
  File "DensePose/detectron/tests/test_zero_even_op.py", line 117, in <module>
    c2_utils.import_custom_ops()
  File "/home/sriram/DensePose/detectron/utils/c2.py", line 40, in import_custom_ops
    dyndep.InitOpsLibrary(custom_ops_lib)
  File "/home/sriram/anaconda2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/home/sriram/anaconda2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/home/sriram/anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sriram/DensePose/build/libcaffe2_detectron_custom_ops_gpu.so: undefined symbol: _ZN6caffe219CPUOperatorRegistryB5cxx11Ev
`
Tried to install gcc-4.9.2 and ended up facing error for so may possible times, also when i ran using colab, there they just installed gcc-4.9.1 but default gcc is 7.5.0

so i just skipped  `test_zero_even_op.py` and tried to run in infer mode , even there i faced some errors like

`RuntimeError: [enforce fail at context_gpu.cu:415] error == cudaSuccess. 2 vs 0. Error at: /opt/conda/conda-bld/pytorch_1549617926868/work/caffe2/core/context_gpu.cu:415: out of memory
`
please check this thread [https://github.com/facebookresearch/DensePose/issues/269] 

i was trying from the last 7days , it is really painful 
please help me out.
